# Generated by Django 3.2 on 2022-05-11 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.IntegerField(choices=[(1, 'MOBILE'), (2, 'TABLE'), (3, 'PORTABLE'), (4, 'DESKTOP'), (0, 'OTHER')], default=1)),
                ('model', models.CharField(max_length=150)),
                ('manufacturer', models.CharField(max_length=150)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MacAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=20, unique=True)),
                ('type', models.IntegerField(choices=[(1, 'WIFI'), (2, 'BLE'), (0, 'OTHER')], default=1)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.IntegerField(choices=[(0, 'OUTSIDE'), (1, 'INSIDE'), (2, 'PENDING')], default=0)),
                ('enable', models.IntegerField(choices=[(0, 'FALSE'), (1, 'TRUE')], default=0)),
                ('photo', models.CharField(max_length=550)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(choices=[(0, 'OUTSIDE'), (1, 'INSIDE'), (2, 'PENDING')], default=0)),
                ('device_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.device')),
                ('profile_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='mac_address_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.macaddress'),
        ),
    ]
