# Generated by Django 3.2 on 2022-05-10 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(choices=[(0, 'Main'), (1, 'Other')], default=0)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('mac', models.CharField(max_length=20)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(0, 'OUTSIDE'), (1, 'INSIDE'), (2, 'PENDING')], default=0)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('device_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.device')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
