# Generated by Django 3.2 on 2022-05-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.IntegerField(choices=[(0, 'OUTSIDE'), (1, 'INSIDE'), (2, 'PENDING')], default=2),
        ),
        migrations.AlterField(
            model_name='profiledevice',
            name='priority',
            field=models.IntegerField(choices=[(0, 'LOW'), (1, 'MEDIUM'), (2, 'HIGH')], default=0),
        ),
    ]
