# Generated by Django 3.2 on 2022-05-11 12:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220511_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledevice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profiledevice',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
