# Generated by Django 3.2 on 2022-05-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220511_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='enable',
            field=models.IntegerField(choices=[(0, 'FALSE'), (1, 'TRUE')], default=1),
        ),
    ]
